### ISSUE TITLE
Bedingte Wahrscheinlichkeiten.Urne mit Loch

### ISSUE THREAD

**Issue by RKir** [jwergieluk/problem-extractor#2]
1a) P(W2) müsste durch P(W1) ersetzt werden

1b) bezüglich P(W)=Summe... in der 2. Zeile müsste im Nenner w+s-d stehen statt w+s-i, da ja alle verlorenen Kugeln (d) aus der Gesamtmenge verschwinden, nicht nur die verlorenen weißen Kugeln (i)

**Comment by jwergieluk** [comment]
Danke für die Hinweise. Beides korrigiert. Allerdings befinden sich die Aufgaben in dem repo problem-pool https://github.com/jwergieluk/problem-pool
